set nocompatible

filetype plugin indent on

" Color scheme
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
call plug#end()

syntax on
colorscheme gruvbox
set background=dark

" General
set title
set ruler
set number
set relativenumber
set wildmenu
set showmatch
set lazyredraw
set mouse=a
set clipboard=unnamedplus

" Searching
set incsearch
set hlsearch
set ignorecase
set smartcase
nnoremap i :noh<cr>i

" Tabs and indentation
set tabstop=8
set shiftwidth=4
set expandtab
set softtabstop=4
set shiftround

" Move cursor independent of text wrap
nnoremap j gj
nnoremap k gk

" Insert single character before cursor
nnoremap <Space> i_<Esc>r

" Switch to normal mode
" inoremap jk <Esc>

" Spelling (requires ~/.vim/spell to already exist)
set spell spelllang=en_us
set spellfile=~/.vim/spell/en.utf-8.add
hi SpellBad cterm=underline

" Persistent undo (requires ~/.vim/undodir to already exist)
set undodir=~/.vim/undodir
set undofile

" Jump to last known cursor position
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
